#!/bin/sh
DEVICES="$@"

echo multidisk ::
for DEVICE in $DEVICES ; do
    if [ "$DEVICE" = "/dev/sda" ]
    then
	continue
    fi
    cat partman_pvs.cfg|sed -E "s|\\\$DEVICE|$DEVICE|g"
done
cat partman_lvs.cfg
