#!/bin/bash

DT="$(date --utc --iso-8601=seconds)"
BOOTPATH=boot

rm -rf "$BOOTPATH"
mkdir "$BOOTPATH"
cp -f fetch/linux "$BOOTPATH/linux"
cp -f fetch/initrd.gz "$BOOTPATH/initrd.gz"

# add shutdown hook
cd "$BOOTPATH"
gzip -d initrd.gz
cpio -H newc -F initrd -idmv etc/inittab
echo '::shutdown:cat /var/log/syslog' >>etc/inittab
echo etc/inittab|cpio -H newc -F initrd -oAv
gzip initrd
cd -

# add preseed
ls ./preseed.cfg ./setmirror.sh|cpio -H newc -o|gzip >>"$BOOTPATH/initrd.gz"

# create system image hd
rm -f "$BOOTPATH/sys.img"
qemu-img create -f qcow2 "$BOOTPATH/sys.img" 500M

qemu-system-aarch64 \
    -d unimp,guest_errors \
    -D qemu.log \
    -serial mon:stdio \
    -machine virt,virtualization=true,kernel_irqchip=on,gic-version=3 \
    -bios "/data/data/com.termux/files/usr/share/qemu/edk2-aarch64-code.fd" \
    -cpu cortex-a53 \
    -m 512M \
    -kernel "$BOOTPATH/linux" \
    -initrd "$BOOTPATH/initrd.gz" \
    -append "earlyprintk=serial console=ttyAMA0 BOOT_DEBUG=0 DEBIAN_FRONTEND=text debconf/priority=critical auto-install/enable=true" \
    -nographic \
    -netdev user,id=net0 \
    -device driver=virtio-net-pci,netdev=net0 \
    -object rng-random,filename=/dev/urandom,id=rng0 \
    -device virtio-rng-pci,rng=rng0 \
    -rtc base=utc,clock=host \
    -device virtio-scsi-pci,id=scsi0 \
    -device scsi-hd,drive=syshd,bus=scsi0.0,channel=0,scsi-id=0,lun=0 \
    -drive file="$BOOTPATH/sys.img",format=qcow2,if=none,id=syshd
#    -cdrom https://nl.alpinelinux.org/alpine/latest-stable/releases/aarch64/alpine-standard-3.13.5-aarch64.iso
#    -machine dumpdtb=virt.dtb \
#    -bios /data/data/com.termux/files/usr/share/qemu/edk2-aarch64-code.fd \
#    -append "earlyprintk=serial console=ttyAMA0 init=/bin/ash" \
#    -append "earlyprintk=serial console=ttyAMA0 DEBIAN_FRONTEND=text debconf/priority=low" \
    
reset
