#!/bin/bash
echo PWD: $PWD
ls -l
BOOTPATH="$1"
ORIGDIR="${PWD}"
BOXNAME="${REPO_NAME}"
IMAGE="${ORIGDIR}/image-vagrant/${BOXNAME}"
mkdir -p "${IMAGE}"
echo cd "${BOOTPATH}"
cd "${BOOTPATH}"
for img in *.img; do
    qemu-img convert -p -f qcow2 -O vmdk "${img}" "${IMAGE}/${img%.*}.vmdk"
done
cd "../vagrant"
cp -a * "${IMAGE}"
cd "${IMAGE}"
tar -cvzf "../${BOXNAME}.box" .
cd ..
rm -rf "${IMAGE}"
md5sum * >.MD5SUMS
mv .MD5SUMS MD5SUMS
