#!/bin/bash

if ! [ $# -eq 5 ]; then
    APP_NAME="$(basename $0)"
    echo "${APP_NAME}: usage is: ${APP_NAME} {QEMU_ARCH} {QEMU_MACH} {QEMU_CPU} {TIMEOUT} {SYS_SIZE} {IMAGE_SUBVERSION}"
    echo -e "QEMU_ARCH:\tQEMU systemn target platform"
    echo -e "QEMU_MACH:\tQEMU system target machine"
    echo -e "QEMU_CPU:\tQEMU system target CPU"
    echo -e "TIMEOUT:\tBuild time in minutes before machine is powered off"
    echo -e "SYS_SIZE:\tTotal system disks size in GBi"
    echo -e "IMAGE_SUBVERSION:\Suffix version for file /etc/image_version"
    exit 1
fi

DT="$(date --utc --iso-8601=seconds)"
BOOTPATH="$(pwd)/${BOOTPATH:-boot}"
QEMU_ARCH="$1"
QEMU_MACH="$2"
QEMU_CPU="$3"
TIMEOUT="$((($4-5)*60))"
# ceiling of system image size if decimal
SYS_COUNT="$(echo $5|awk 'function ceil(v) { return v%1?int(v)+1:v } { a=ceil($1/1.5) } ; { print ceil(a) }')"
IMAGE_SUBVERSION="$6"

rm -rf "$BOOTPATH"
mkdir "$BOOTPATH"
cp -f fetch/linux "$BOOTPATH"
cp -f fetch/initrd.gz "$BOOTPATH"
# cp -f edk2-aarch64-code.fd.bz2 "$BOOTPATH"
# bzip2 -d "$BOOTPATH/edk2-aarch64-code.fd.bz2"

# add shutdown hook
cd "$BOOTPATH"
gzip -d initrd.gz
cpio -H newc -F initrd -idmv etc/inittab
echo '::shutdown:/onfail.sh' >>etc/inittab
echo etc/inittab|cpio -H newc -F initrd -oAv
gzip initrd
cd -

cd preseed
# set watchdog
sed "s/TIMEOUT/${TIMEOUT}/g" -i ./watchdog.sh
echo "WATCHDOG: timeout = $TIMEOUT"
# add preseed files
ls ./* \
    |cpio -H newc -R +0:+0 -o|gzip >>"$BOOTPATH/initrd.gz"
cd -

# create system image hd
for i in $(seq 1 "${SYS_COUNT}"); do rm -f "$BOOTPATH/sys_$i.img"; done
for i in $(seq 1 "${SYS_COUNT}"); do qemu-img create -f qcow2 "$BOOTPATH/sys_$i.img" 1.5G; done
ls -l "$BOOTPATH"

case "${QEMU_ARCH}" in
    aarch64)
	CONSOLE=ttyAMA0
	;;
    *)
	CONSOLE=ttyS0
	;;
esac

"qemu-system-${QEMU_ARCH}" \
    -d unimp,guest_errors \
    -D qemu.log \
    -serial mon:stdio \
    -machine "${QEMU_MACH}" \
    -cpu "${QEMU_CPU}" \
    -m 1024M \
    -kernel "$BOOTPATH/linux" \
    -initrd "$BOOTPATH/initrd.gz" \
    -append "earlyprintk=serial console=${CONSOLE} consoleblank=0 elevator=noop scsi_mod.use_blk_mq=Y net.ifnames=0 biosdevname=0 - BOOT_DEBUG=1 DEBIAN_FRONTEND=text debconf/priority=critical auto-install/enable=true IMAGE_SUBVERSION=${IMAGE_SUBVERSION}" \
    -nographic \
    -netdev user,id=net0 \
    -device driver=virtio-net-pci,netdev=net0 \
    -object rng-random,filename=/dev/urandom,id=rng0 \
    -device virtio-rng-pci,rng=rng0 \
    -rtc base=utc,clock=host \
    -device virtio-scsi-pci,id=scsi0 \
    -device scsi-hd,drive=syshd,bus=scsi0.0,channel=0,scsi-id=0,lun=0 \
    -drive file="$BOOTPATH/sys_1.img",format=qcow2,if=none,id=syshd
#    -cdrom https://nl.alpinelinux.org/alpine/latest-stable/releases/aarch64/alpine-standard-3.13.5-aarch64.iso
#    -machine dumpdtb=virt.dtb \
#    -bios "edk2-aarch64-code.fd" \
#    -append "earlyprintk=serial console=ttyAMA0 init=/bin/ash" \
#    -append "earlyprintk=serial console=ttyAMA0 DEBIAN_FRONTEND=text debconf/priority=low" \

# if terminal then reset
if [ -t 0 -a -t 1 -a -t 2 ]
then
    reset
fi
