#!/bin/bash
echo PWD: $PWD
BOOTPATH="$1"
ORIGDIR="${PWD}"
BOXNAME="${REPO_NAME}"
IMAGE="${ORIGDIR}/image-vagrant/${BOXNAME}"
mkdir -p "${IMAGE}"
echo cd "${BOOTPATH}"
cd "${BOOTPATH}"
for img in *.img; do
    cp "${img}" "${IMAGE}/${img}"
done
cd "${ORIGDIR}/vagrant"
cp -a * "${IMAGE}"
cd "${IMAGE}"
METADATA_JSON="$(cat metadata.json|jq '. += {disks: []}')"|jq '.disks += [$ARGS.named]' --arg path 'Banana'|jq '.disks += [$ARGS.named]' --arg path 'Apple'
for img in *.img; do
    METADATA_JSON="$(echo $METADATA_JSON|jq '.disks += [$ARGS.named]' --arg path '$img')"
done
echo "$METADATA_JSON" >metadata.json
pwd
tar -cvzf "../${BOXNAME}.box" .
cd ..
rm -rf "${IMAGE}"
md5sum * >.MD5SUMS
mv .MD5SUMS MD5SUMS
