#!/bin/bash
IMAGE="${PWD}/image-qemu-${IMAGE_VERSION}"
mkdir "${IMAGE}"
cd "${BOOTPATH}"
echo cp * "${IMAGE}"
cp * "${IMAGE}"
echo cd "${IMAGE}"
cd "${IMAGE}"
md5sum * >.MD5SUMS
mv .MD5SUMS MD5SUMS
cd -
