#!/bin/bash
echo PWD: $PWD
ls -l
IMAGE="${PWD}/image-qemu"
mkdir "${IMAGE}"
echo cd "${BOOTPATH}"
cd "${BOOTPATH}"
ls -Rl
tar -cvzf data.tar.gz data
rm -rf data linux initrd.gz
echo cp * "${IMAGE}"
cp * "${IMAGE}"
echo cd "${IMAGE}"
cd "${IMAGE}"
md5sum * >.MD5SUMS
mv .MD5SUMS MD5SUMS
cd -
