#!/bin/bash
NETBOOT_ROOT="https://deb.debian.org/debian/dists/stable/main/installer-arm64/current/images"
NETBOOT_URL="$NETBOOT_ROOT/netboot/debian-installer/arm64"
curl "$NETBOOT_ROOT/MD5SUMS"
echo curl -O "$NETBOOT_URL/linux"
echo curl -O "$NETBOOT_URL/initrd.gz"
