#!/bin/bash

function get_md5_remote
{
    local REMOTE_FILE="$1"
    grep "$REMOTE_FILE" MD5SUMS|awk '{print $1}'
}

function get_md5_local
{
    local LOCAL_FILE="$1"
    md5sum "$LOCAL_FILE"|awk '{print $1}'
}

function check_md5
{
    local REMOTE_FILE="$1"
    local LOCAL_FILE="$2"
    [ "$(get_md5_remote $REMOTE_FILE)" = "$(get_md5_local $LOCAL_FILE)" ]
}

[ -d image ] || mkdir image
gh run download -n dockemu-arm64 -D image
exit 0
