#!/bin/bash

curl \
  --request GET \
  --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
  https://app.vagrantup.com/api/v2/box/andreazuccherelli/debian-basevm/version/0.0.1/provider/virtualbox/amd64
