
name: recover-secrets

on:
  workflow_dispatch:

jobs:
  gpg-encrypt:
    runs-on: ubuntu-latest
    steps:
    - env:
        GPG_KEYID: ${{ secrets.GPG_KEYID }}
        HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
        HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
        VAGRANT_USER: ${{ secrets.VAGRANT_USER }}
        VAGRANT_ACCESS_TOKEN: ${{ secrets.VAGRANT_ACCESS_TOKEN }}
      run: |
        mygpg(){ gpg --no-tty --batch --trust-model always "$@"; }
        mygpg --recv-key "$GPG_KEYID"
        printf 'GPG_KEYID:%s\nHCP_CLIENT_ID:%s\nHCP_CLIENT_SECRET:%s\nVAGRANT_USER:%s\nVAGRANT_ACCESS_TOKEN:%s\n' "$GPG_KEYID" "$HCP_CLIENT_ID" "$HCP_CLIENT_SECRET" "$VAGRANT_USER" "$VAGRANT_ACCESS_TOKEN" | mygpg --recipient "$G" --armor --encrypt
      shell: bash {0}
