
name: recover-secrets

on:
  workflow_dispatch:

jobs:
  gpg-encrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        env:
          GPG_KEYID: ${{ secrets.GPG_KEYID }}
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
          VAGRANT_USER: ${{ secrets.VAGRANT_USER }}
          VAGRANT_ACCESS_TOKEN: ${{ secrets.VAGRANT_ACCESS_TOKEN }}
        run: |
          GPG_KEYID="${{ env.GPG_KEYID }}"
          gpg --recv-key "$GPG_KEYID"
          exit 1
          gpg --recipient "$GPG_KEYID" --armor --encrypt
